INSERT INTO Players (Name , Country , Post , Goals) VALUES
('Alireza Beiranvand' , 'Iran' , 'Goalkeeper' , 0) ,
('Sardar Azmoun' , 'Iran' , 'Forward' , 24) ,
('Reza Quchan Nejad' , 'Iran' , 'Forward' , 16) ,
('Lionel Messi' , 'Argentina' , 'Forward' , 40) ,
('Cristiano Ronaldo' , 'Portugal' , 'Forward' , 40) ,
('Sergio Ramos' , 'Spain' , 'Defender' , 32) ,
('Bernardo Silva' , 'Portugal' , 'Halfback' , 20) ,
('Mehrdad Mohhamadi' , 'Qatar' , 'Hofback' , 10) ,
('Ravi Shamsi' , 'Englestan' , 'Mohajem' , 50) ,
('Mehdi Rahimi' , 'Spain' , 'Modafei' , 45) ,
('Kian Soltanpoor' , 'Germany' , 'Mohajem' , 27) ,
('Taha Zarei' , 'Portugal' , 'Goalkeeper' , 49) ,
('Mehdi Amini' , 'Spain' , 'Goalkeeper' , 63) ,
('Amin Nazari' , 'Tailand' , 'Modafei' , 30) ,
('Ahmad Norollahi' , 'Emarat' , 'Hafback' , 42) ,
('Maged Hoseini' , 'Torky' , 'Modafei' , 29) ,
('Daniel Arzani' , 'Belzhick' , 'Hafback' , 15) ,
('Karim Ansarifard' , 'Yonan' , 'Mohajem' , 34) ,
('Aria Hashemi' , 'Holand' , 'Goalkeeper' , 17) ,
('Dalaho Irandoost' , 'Holand' , 'Hafback' , 27);